In [14]:

import duckdb
file = "C:/Users/manat/Documents/Projects/mtlBiodiversity/data/db/mtlbio.duckdb"
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import DBSCAN, HDBSCAN

In [15]:
con = duckdb.connect(file)
df_grid= con.execute("SELECT * from grid_sjoin").df()
df_raw = con.execute("SELECT * from gbif_raw").df()
#df.head()

In [30]:
df_ids = df_grid.loc[df_grid['grid_id'] == 34294]
df_ids = df_ids['gbifID']
df_ids

6772      4507879014
6773      4522527516
6774      4908971906
6775      4910929014
6776      5292329385
             ...
199290    4908924318
199291    4519153732
199292    5292495509
199293    5828128798
199294    5217057527
Name: gbifID, Length: 1534, dtype: int64

In [ ]:
df_filtered = df_raw.merge(df_ids, on='gbifID', how='inner')

df_filtered.shape

In [28]:
df_filtered.head()

,gbifID,occurrenceID_x,kingdom_x,phylum_x,class_x,order_x,family_x,genus_x,species_x,taxonRank_x,...,typeStatus,establishmentMeans,lastInterpreted,mediaType,issue_y,geom_y,minx_y,miny_y,maxx_y,maxy_y
0,4507879014,https://www.inaturalist.org/observations/19510...,Animalia,Arthropoda,Insecta,Lepidoptera,Crambidae,Crambus,Crambus praefectellus,SPECIES,...,None,None,2025-09-23 09:29:47.812000-04:00,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",-73.607343,45.595636,-73.607343,45.595636
1,4522527516,https://www.inaturalist.org/observations/19840...,Animalia,Arthropoda,Insecta,Lepidoptera,Noctuidae,Papaipema,Papaipema impecuniosa,SPECIES,...,None,None,2025-09-23 09:31:02.891000-04:00,StillImage;StillImage;StillImage;StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",-73.607334,45.595616,-73.607334,45.595616
2,4908971906,https://www.inaturalist.org/observations/22930...,Animalia,Arthropoda,Insecta,Lepidoptera,Crambidae,Microcrambus,Microcrambus elegans,SPECIES,...,None,None,2025-09-23 09:40:50.927000-04:00,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",-73.607340,45.595630,-73.607340,45.595630
3,4910929014,https://www.inaturalist.org/observations/22892...,Animalia,Arthropoda,Insecta,Lepidoptera,Erebidae,Halysidota,Halysidota tessellaris,SPECIES,...,None,None,2025-09-23 08:01:53.260000-04:00,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",-73.606698,45.595659,-73.606698,45.595659
4,5292329385,https://www.inaturalist.org/observations/30458...,Animalia,Arthropoda,Insecta,Lepidoptera,Crambidae,Eudonia,Eudonia strigalis,SPECIES,...,None,None,2025-09-23 08:25:14.781000-04:00,StillImage,COORDINATE_ROUNDED;CONTINENT_DERIVED_FROM_COOR...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...",-73.607345,45.595633,-73.607345,45.595633

In [ ]:
df_obs.to

In [17]:
con.close()